version: '3'
services:
  db:
    image: mariadb:latest
    env_file:
      - .dbenv
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - internal

  redis:
    image: redis:latest
    container_name: redis
    networks:
      - internal

  pretix:
    build: .
    volumes:
      - pretix-data:/data
      - static-data:/pretix/src/pretix/static.dist
    depends_on:
      - db
      - redis
    command: ./pretix-entrypoint.sh
    user: www-data
    ports:
      - "8000"
    networks:
      - internal
      - external
    environment:
      VIRTUAL_HOST: pretix.chaos-party-ulm.de,tickets.chaos-party-ulm.de
      LETSENCRYPT_HOST: pretix.chaos-party-ulm.de,tickets.chaos-party-ulm.de
      LETSENCRYPT_EMAIL: le@maxrink.de
  task:
    build: .
    volumes:
      - pretix-data:/data
      - static-data:/static
    depends_on:
      - pretix
    command: ./task-entrypoint.sh
    user: www-data
    networks:
      - internal
      
  nginx-web:
    image: nginx
    labels:
        com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
    container_name: nginx-web
    restart: always
    ports:
      - "0.0.0.0:80:80"
      - "0.0.0.0:443:443"
    volumes:
      - nginx-conf:/etc/nginx/conf.d
      - nginx-vhosts:/etc/nginx/vhost.d
      - nginx-webroot:/usr/share/nginx/html
      - nginx-certs:/etc/nginx/certs:ro
      - nginx-htpasswd:/etc/nginx/htpasswd:ro
    depends_on:
      - pretix
    networks:
      - external 


  nginx-gen:
    image: jwilder/docker-gen
    command: -notify-sighup nginx-web -watch -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    container_name: nginx-gen
    restart: always
    volumes:
      - nginx-conf:/etc/nginx/conf.d
      - nginx-vhosts:/etc/nginx/vhost.d
      - nginx-webroot:/usr/share/nginx/html
      - nginx-certs:/etc/nginx/certs:ro
      - nginx-htpasswd:/etc/nginx/htpasswd:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro


  nginx-letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: nginx-letsencrypt
    restart: always
    volumes:
      - nginx-conf:/etc/nginx/conf.d
      - nginx-vhosts:/etc/nginx/vhost.d
      - nginx-webroot:/usr/share/nginx/html
      - nginx-certs:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      NGINX_DOCKER_GEN_CONTAINER: nginx-gen
      NGINX_PROXY_CONTAINER: nginx-web

volumes:
  pretix-data:
  db-data:
  static-data:
  nginx-certs:
  nginx-vhosts:
  nginx-webroot:
  nginx-conf:
  nginx-htpasswd:
  
networks:
  internal:
  external: